Add spy node ban list
lalanza808/docker-monero-node pull request #28
Opened 2024-12-12 09:28 UTC by nyuuzyou

> The Monero Research Lab (MRL) https://github.com/monero-project/meta/issues/1119 to recommend that all Monero node operators enable a ban list of suspected spy node IP addresses. The spy nodes can reduce the privacy of Monero users.

https://github.com/monero-project/meta/issues/1124

2024-12-12 21:20 UTC, Dvd-Znf approved these changes

2024-12-12 21:41 UTC, Dvd-Znf requested changes

2024-12-12 21:41 UTC, Dvd-Znf commented on dockerfiles/monero
>    && apt-get install -y tar wget bzip2
```suggestion
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y tar wget bzip2
  
  RUN wget -qO /ban_list.txt "https://raw.githubusercontent.com/Boog900/monero-ban-list/main/ban_list.txt"
```
  
wget needs to be installed before ran,

2024-12-13 04:16 UTC, merged

2024-12-13 05:02 UTC, lalanza808 commented
thanks for your contribution